#### ==================== SIMULATE JUNCTION EVAPORATION ==================== ###
evaporation:
  junctions:
    number: 100
    overlap: [5, 0.2]
    wire: [0.4, 0.25]
    undercut: 0.8
    undercut_after_JJ: 1.2
  layers: [4, 5]
  source:
    distance: 390.0e3
  resist:
    residual_undercut: 0.05
    upper_photoresist_thickness: 0.18
    lower_photoresist_thickness: 0.72
  angles:
    theta: 45
    phi: ['-x', '+x']